### ISSUE TITLE
regexp goes wrong  with nested math tags

### ISSUE THREAD

**Issue by QiShao647** [zlqm/docx-equation#3]
`_omath_pattern = re.compile(r'<m:oMath[^<>]*>.+?</m:oMath>', flags=re.S)`
this line incorrectly  matches <m:oMathPara> and </m:oMath> if we have nested math tags below.
![image](https://user-images.githubusercontent.com/26427602/130786921-a9cc1f4e-990f-4e57-bb39-51c0c3fcd232.png)

perhaps simply revert the sequence of two regexps solves this issue.

`    xml_content = _omath_para_pattern.sub(lambda m: m.group(1), xml_content)`
`    xml_content = _omath_pattern.sub(replace, xml_content)`

**Comment by zlqm** [comment]
may be just change `<m:oMath[^<>]*>` to `<m:oMath(?:\s[^<>]*)?>` can solve this problem.

```python
_omath_pattern = re.compile(r'<m:oMath(?:\s[^<>]*)?>.+?</m:oMath>', flags=re.S)
```

**Comment by QiShao647** [comment]
it works perfectly:)
